### ISSUE TITLE
File Upload guide doesn't work

### ISSUE THREAD

**Issue by mamantoha** [kemalcr/kemalcr.com#12]
File Upload guide (http://kemalcr.com/docs/file_upload/) doesn't work with Kemal 0.18.1

```
undefined method 'filename' for Tempfile

  file_path = ::File.join [Kemal.config.public_folder, "uploads/", file.filename]
```

**Comment by sdogruyol** [comment]
I just updated the docs 👍
